name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install package and test/runtime dependencies so pytest is available
          python -m pip install -e .
          pip install pytest python-dotenv langchain-google-genai
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Install code formatter
        run: pip install black
      - name: Check code style with black
        run: black --check .
      - name: Run tests
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: pytest -q
